app = "mcp-filesystem"
primary_region = "ams"

[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
