[project]
name = "mcp-filesystem-server"
version = "0.1.0"
description = "Safe-by-default MCP server for filesystem + optional command execution"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "mcp",
]

[tool.ruff]
line-length = 100
